### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by Naveed151214** [NamanAgarwal016/BHEL-Material-Gate-Pass-System#1]
Hello Naman,

i have couple of issues, if you could explain a little bit about the this project.

1. How to deploy and run this application a detailed installation process.
2. How many levels of approvals you have defined in it, can you make it four levels.
3. Where is the database is it possible to attached this project with mysql.
4. I am currently trying to run it through Xampp sever to check how it works.
5. There is a form to create users to allow them to create gate pass?

Thanks in advance.

I will be waiting for response.

**Comment by NamanAgarwal016** [comment]
Can you please tell me your purpose for using this project??

**Comment by NamanAgarwal016** [comment]
I cannot share many details of this project as it is related to a company's internship project, which they currently are using on their intranet.

**Comment by Naveed151214** [comment]
I understand, its okay then I was trying to develop same type of project. No worries I will try to search some other example there are many.

Thanks.
